#!/usr/bin/env python3

## NB: this script is mistly generated by Copilot

import sys
import csv
from pathlib import Path

PROJECT_ROOT = "/margrethe/OFIQ-Project"
IMG_EXTS = {".jpg", ".jpeg", ".png"}


def iter_images(root: Path):
    for p in root.rglob("*"):
        if p.is_file() and p.suffix.lower() in IMG_EXTS:
            yield p


def main():
    import argparse

    ap = argparse.ArgumentParser(
        description="Batch extract OFIQ bounding boxes to CSV for all images under an input folder tree."
    )
    ap.add_argument("--input", required=True, help="Input root directory (folders with images)")
    ap.add_argument("--output_csv", required=True, help="Output CSV path")
    args = ap.parse_args()

    input_dir = Path(args.input).resolve()
    output_csv = Path(args.output_csv).resolve()
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    sys.path.append(str(Path(PROJECT_ROOT) / "python"))
    from ofiq_zmq import OfiqZmq

    images = sorted(iter_images(input_dir))
    if not images:
        print(f"[!] No images found under: {input_dir}")
        return

    print(f"[*] Input root:   {input_dir}")
    print(f"[*] Images found: {len(images)}")
    print(f"[*] Output CSV:   {output_csv}")

    ofiq = OfiqZmq(PROJECT_ROOT)

    try:
        with output_csv.open("w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["image_path", "bbox_x", "bbox_y", "bbox_w", "bbox_h"])

            for img_path in images:
                try:
                    r = ofiq.process_image(str(img_path))
                    bb = None if r is None else r.get("bounding_box", None)

                    if bb is not None:
                        writer.writerow([
                            str(img_path),
                            int(bb.xleft),
                            int(bb.ytop),
                            int(bb.width),
                            int(bb.height),
                        ])
                    else:
                        writer.writerow([str(img_path), "", "", "", ""])

                except Exception as e:
                    print(f"[WARN] Failed for {img_path}: {e}")
                    writer.writerow([str(img_path), "", "", "", ""])
    finally:
        ofiq.shutdown()

    print("[✓] Done.")


if __name__ == "__main__":
    main()